[package]
name = "algo-trading"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "getorderbook"
path = "src/getOrderbook.rs"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
dotenv = "0.15"